### ISSUE TITLE
Optgroup

### ISSUE THREAD

**Issue by mlaplante** [Josizzle/Repository#5]
For this exercise optgroup may be overkill, you can just keep the options inside of the select element and remove the optgroup

**Comment by Josizzle** [comment]
Just fixed those issues you mentioned uploading my correction into Github
now

On Tue, Jan 13, 2015 at 9:19 PM, Michael La Plante <notifications@github.com

**Comment by mlaplante** [comment]
Remove the option with a label attribute on it. Not needed.

Should be something like this:

Select
   option
   option
   option
/Select
