### ISSUE TITLE
Footer is still inside your form

### ISSUE THREAD

**Issue by mlaplante** [Josizzle/Repository#7]
Move your closing form above the footer element start

**Comment by Josizzle** [comment]
Changes have been made and uploaded to github

On Wed, Jan 14, 2015 at 2:27 PM, Michael La Plante <notifications@github.com

**Comment by Josizzle** [comment]
Mike,
Just uploaded what I could do from Homework 3. I am struggling a little bit
and behind on the videos. I need some help. Will come into class little bit
early today and stay later if need be.

**Comment by Josizzle** [comment]
Just uploaded what I have for assignment homework 3 so far. having some
trouble but I have more videos to watch. Will work on it tonight for sure.

**Comment by Josizzle** [comment]
Just uploaded Homework assignment #3. Ready for review
